removeed envs

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -57,8 +57,8 @@ jobs:
           BRANCH_NAME=$(echo $GITHUB_REF | sed 's|refs/heads/||' | sed 's|/|-|g' | sed 's|env:/||g') 
           TF_STATE_KEY="${BRANCH_NAME}.tfstate"  
           echo "TF_STATE_KEY=${TF_STATE_KEY}" >> $GITHUB_ENV  
-          terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${{env.TF_STATE_KEY}}" -backend-config="region=${AWS_REGION}"
-          terraform workspace select "${{env.BRANCH_NAME}}" || terraform workspace new "${{env.BRANCH_NAME}}"
+          terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${TF_STATE_KEY}" -backend-config="region=${AWS_REGION}"
+          terraform workspace select "${BRANCH_NAME}" || terraform workspace new "${BRANCH_NAME}"
       
       - name: Terraform Validate
         id: validate
@@ -127,11 +127,11 @@ jobs:
           AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
         run: | # doing this to get clean name without / and then get a terraform safe name
            BRANCH_NAME=$(echo $GITHUB_REF | sed 's|refs/heads/||' | sed 's|/|-|g')  
-           terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${{ env.TF_STATE_KEY }}" -backend-config="region=${AWS_REGION}"
+           terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${TF_STATE_KEY}" -backend-config="region=${AWS_REGION}"
            
       - name: Select Terraform Workspace
         run: |
-         terraform workspace select ${{env.BRANCH_NAME}} || echo "Workspace not found, skipping."
+         terraform workspace select ${BRANCH_NAME} || echo "Workspace not found, skipping."
 
       - name: Debug Terraform State
         run: terraform state list || echo "No state found for this branch."
