clean

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -109,15 +109,15 @@ jobs:
         if: ${{ github.event.pull_request != null }}
         run: |
           DELETE_BRANCH_NAME=${{ github.event.pull_request.head.ref }}
-          BRANCH_NAME=$(echo $DELETE_BRANCH_NAME | sed 's|/|-|g')  
+          BRANCH_NAME=$(echo $DELETE_BRANCH_NAME | sed 's|/|-|g')  >> $Github_ENV
           echo "Branch that was merged: ${BRANCH_NAME}"
           echo "TF_STATE_KEY=env:/${BRANCH_NAME}/${BRANCH_NAME}.tfstate" >> $GITHUB_ENV
 
       - name: Set Terraform State File for Cleanup (Deleted branch)
         if: ${{ github.event_name == 'push' && github.event.delete.ref != null }}
         run: |
-          DELETE_BRANCH_NAME=$(echo $GITHUB_REF | sed 's|refs/heads/||')
-          BRANCH_NAME=$(echo $DELETE_BRANCH_NAME | sed 's|/|-|g')
+          DELETE_BRANCH_NAME=$(echo $GITHUB_REF | sed 's|refs/heads/||') 
+          BRANCH_NAME=$(echo $DELETE_BRANCH_NAME | sed 's|/|-|g') >> $Github_ENV
           echo "Branch that was deleted: ${BRANCH_NAME}"
           echo "TF_STATE_KEY=env:/${BRANCH_NAME}/${BRANCH_NAME}.tfstate" >> $GITHUB_ENV
 
@@ -132,7 +132,7 @@ jobs:
            
       - name: Select Terraform Workspace
         run: |
-         terraform workspace select ${DELETE_BRANCH_NAME} || echo "Workspace not found, skipping."
+         terraform workspace select ${BRANCH_NAME} || echo "Workspace not found, skipping."
 
       - name: Debug Terraform State
         run: terraform state list || echo "No state found for this branch."
