updated clean job

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -19,6 +19,7 @@ env:
 
 jobs:
   deploy:
+    if: github.event.pull_request.merged != true && github.event.pull_request.base.ref != 'master'
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -52,7 +53,8 @@ jobs:
           AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
         run: | # doing this to get clean name without / and then get a terraform safe name
            BRANCH_NAME=$(echo $GITHUB_REF | sed 's|refs/heads/||' | sed 's|/|-|g')  
-           terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="region=${AWS_REGION}"
+           terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=feature-${GITHUB_REF}.tfstate" -backend-config="region=${AWS_REGION}"
+
            
            terraform workspace select ${BRANCH_NAME} || terraform workspace new ${BRANCH_NAME}
 
@@ -103,10 +105,19 @@ jobs:
       - name: Set Terraform State File for Cleanup
         run: |
           DELETE_BRANCH_NAME=${{ github.event.pull_request.head.ref }} 
+          echo "Branch that was deleted : ${DELETE_BRANCH_NAME}"
           echo "TF_STATE_KEY=feature-${DELETE_BRANCH_NAME}.tfstate" >> $GITHUB_ENV
 
       - name: Terraform Init
-        run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=feature-${DELETE_BRANCH_NAME}.tfstate" -backend-config="region=${AWS_REGION}"
+        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=feature-${DELETE_BRANCH_NAME}.tfstate" -backend-config="region=${AWS_REGION}"
+
+
+      - name: Select Terraform Workspace
+        run: |
+         terraform workspace select ${DELETE_BRANCH_NAME} || echo "Workspace not found, skipping."
+
+      - name: Debug Terraform State
+        run: terraform state list || echo "No state found for this branch."
 
       - name: Destroy Feature Branch Resources
         run: terraform destroy -auto-approve
